In [1]:
import numpy as np

### Ways to create array in numpy

In [2]:
arr_1 = np.array([4,6,7,4,23,7,8])

In [3]:
arr_1

array([ 4,  6,  7,  4, 23,  7,  8])

In [5]:
arr_2 = np.arange(1,20,3)
print(arr_2)

[ 1  4  7 10 13 16 19]


In [14]:
# arr_3 = np.zeros(5)
# print(arr_3)

arr_3 = np.zeros((2,4))
print(arr_3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
arr_3 = np.ones((2,3))
print(arr_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
arr_4 = np.linspace(0,10,num=20,retstep=True)
print(arr_4)

(array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]), 0.5263157894736842)


In [21]:
arr_5 = np.identity(4)
print(arr_5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
np.random.random()

0.6683858693922687

In [24]:
np.random.random((2,2))

array([[0.77213604, 0.0575149 ],
       [0.33528649, 0.37744344]])

In [26]:
np.random.randn(2,2)

array([[ 0.60099595, -0.44551809],
       [ 1.25479063,  2.04683815]])

In [35]:
# np.random.seed(99)
# np.random.randint(1,10)
np.random.randint(1,100,20)

array([36, 58, 41, 74, 83, 69, 70, 53,  2, 24, 36, 56, 66, 49, 94, 60, 88,
        3, 65, 13])

In [36]:
x = np.random.randint(1,100,20)

In [39]:
x[0:5]

array([41, 73, 21, 60, 40])

In [40]:
x.shape

(20,)

In [42]:
x = x.reshape(5,4)

In [43]:
x

array([[41, 73, 21, 60],
       [40, 80, 48, 28],
       [63, 63, 18, 74],
       [33, 22, 42, 20],
       [23, 27, 51, 60]])

In [44]:
x[0]

array([41, 73, 21, 60])

In [45]:
x[0][0]

41

In [46]:
x[:,0]

array([41, 40, 63, 33, 23])

In [47]:
x[0:2,0:2]

array([[41, 73],
       [40, 80]])

In [50]:
x = x.flatten()

In [51]:
x

array([41, 73, 21, 60, 40, 80, 48, 28, 63, 63, 18, 74, 33, 22, 42, 20, 23,
       27, 51, 60])

In [52]:
x.max()

80

In [53]:
x.min()

18

In [54]:
x.argmax()

5

In [55]:
x.argmin()

10

In [56]:
x.argsort()

array([10, 15,  2, 13, 16, 17,  7, 12,  4,  0, 14,  6, 18, 19,  3,  8,  9,
        1, 11,  5], dtype=int64)

In [57]:
x.mean()

44.35

In [58]:
np.median(x)

41.5

In [60]:
np.vstack(x)

array([[41],
       [73],
       [21],
       [60],
       [40],
       [80],
       [48],
       [28],
       [63],
       [63],
       [18],
       [74],
       [33],
       [22],
       [42],
       [20],
       [23],
       [27],
       [51],
       [60]])