In [10]:
import pandas as pd
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression

In [4]:
data = {
    "reviews" : ["That was really very nice movie","Wastage of money","Superb, really appreciated the acting and story",
                "must watch movie","too boring, no story at all","one of the best movie i have ever seen","great action and graphics",
                "bad bad bad...","average movie with boring script"],
    "sentiments" : ["pos","neg","pos","pos","neg","pos","pos","neg","neg"]
}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

reviews sentiments
0                  That was really very nice movie        pos
1                                 Wastage of money        neg
2  Superb, really appreciated the acting and story        pos
3                                 must watch movie        pos
4                      too boring, no story at all        neg
5           one of the best movie i have ever seen        pos
6                        great action and graphics        pos
7                                   bad bad bad...        neg
8                 average movie with boring script        neg

In [9]:
X = df['reviews']
y = df['sentiments']

In [11]:
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [12]:
cv = CountVectorizer()
vect = cv.fit_transform(X)

In [13]:
vect

<9x34 sparse matrix of type '<class 'numpy.int64'>'
	with 43 stored elements in Compressed Sparse Row format>

In [14]:
reg = LogisticRegression()

In [16]:
reg.fit(vect,y)

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [18]:
reg.predict(vect)

array([1, 0, 1, 1, 0, 1, 1, 0, 0])

In [19]:
y

array([1, 0, 1, 1, 0, 1, 1, 0, 0])

In [20]:
rev = "that was a good movie, worth to watch"

In [22]:
rev= cv.transform([rev])

In [23]:
reg.predict(rev)

array([1])

In [24]:
reg.coef_

array([[ 0.16668174,  0.23731419, -0.21003812,  0.40399594,  0.16668174,
        -0.21003812, -0.28261565, -0.53011887,  0.18028524, -0.49265376,
         0.18028524,  0.23731419,  0.23731419,  0.18028524, -0.32336512,
         0.35758863,  0.27645588,  0.18346316, -0.21003812, -0.14307989,
         0.18028524,  0.3501449 , -0.28261565,  0.18028524, -0.04335638,
         0.16668174,  0.18346316,  0.34696698, -0.21003812,  0.18346316,
         0.18346316, -0.32336512,  0.27645588, -0.28261565]])